name: "Coverity"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: Windows-latest
    container:
      image: fcbrbrazil/coverity:2022.6.0
      credentials:
        username: fcbrbrazil
        password: ${{ secrets.docker_hub_password}}
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Set up Visual Studio environment
      uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    

    # Perform Static Analysis
    - name: Polaris (SAST)
      run: |
        cov-build --dir idir --fs-capture-search . msbuild build
        cov-analyze --dir idir --all --webapp-security --enable-audit-mode
