name: Black Duck - Rapid Scan

on:
  workflow_dispatch

jobs:
  build:
    runs-on: Windows-latest
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Set up Visual Studio environment
      uses: ilammy/msvc-dev-cmd@v1
        
     # Perform Software Composition Analysis - Rapid scan                    
    - name: Black Duck (SCA)
      run: |
          powershell "[Net.ServicePointManager]::SecurityProtocol = 'tls12'; irm https://detect.synopsys.com/detect7.ps1?$(Get-Random) | iex; detect" '--blackduck.url=$env:BLACKDUCK_URL `
          --blackduck.api.token=$BLACKDUCK_API_TOKEN `
           --detect.project.name=sig-demo/WebGoat.NET `
           --detect.project.version.name=main `
           --detect.blackduck.scan.mode=RAPID'
